source 'https://rubygems.org'
#source 'http://gems.rubyforge.org'
gem 'sinatra', '~>1.4.2'
# gem 'dropbox-sdk', '~>1.5.1'
gem 'dropbox_api', '~>0.1.6'
gem 'activesupport', '~>3.2.13'
gem 'tzinfo', '~>0.3.4'
gem 'rdiscount', '~>1.6.8'
